:ruby: ree187
:application: 4tehlulz
:user: rails

:deploy_to: /srv/4tehlulz.biz
:domain: 4tehlulz.biz

:repository: git@github.com:technicalpickles/4tehlulz.biz.git

:shared_children:
- system
- log
- pids
- config

:passenger:
  :max_pool_size: 3

:mysql:
  :innodb_buffer_pool_size: 128M
